# version: '3.9'
services:
  dev-db:
    container_name: sn-dev-db
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - default
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   ports:
  #     - 5050:80
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: viettheog4@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: 123
  #   depends_on:
  #     - dev-db
  #   networks:
  #     - default
  redis:
    container_name: sn-redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - default
networks:
  default:
    name: mvt1927